// names.js — central symbol dictionary: every ticker/ETF/future → long name + description.
// Harry (2026-10-06): 'so I know what I'm seeing.' Display inline, not just tooltip.
//
// Usage:
//   import { symInfo, symName, symNameHtml } from "../names.js";
//   symInfo("TLT") → { name, desc, kind }   (kind: stock|etf|future|other)
//   symName("TLT") → "TLT — iShares 20+ Year Treasury Bond ETF"
//   symNameHtml("TLT") → inline HTML with truncated desc for tight cells

const esc = (s) => String(s ?? "").replace(/[&<>"']/g, (c) =>
  ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));

export const NAMES = {
  TLT: { name: "iShares 20+ Year Treasury Bond ETF", desc: "Long-duration US Treasury bonds", kind: "etf" },
  IEF: { name: "iShares 7-10 Year Treasury Bond ETF", desc: "Intermediate-term US Treasury bonds", kind: "etf" },
  SHY: { name: "iShares 1-3 Year Treasury Bond ETF", desc: "Short-term US Treasury bonds", kind: "etf" },
  SHV: { name: "iShares Short Treasury Bond ETF", desc: "0-1 year US Treasury bills", kind: "etf" },
  BIL: { name: "SPDR Bloomberg 1-3 Month T-Bill ETF", desc: "Ultra-short Treasury bill cash proxy", kind: "etf" },
  TIP: { name: "iShares TIPS Bond ETF", desc: "Treasury inflation-protected securities", kind: "etf" },
  BKLN: { name: "Invesco Senior Loan ETF", desc: "Floating-rate leveraged loans", kind: "etf" },
  LQD: { name: "iShares iBoxx $ Investment Grade Corporate Bond ETF", desc: "US investment-grade corporate credit", kind: "etf" },
  ANGL: { name: "VanEck Fallen Angel High Yield Bond ETF", desc: "Downgraded-to-HY 'fallen angel' bonds", kind: "etf" },
  HYG: { name: "iShares iBoxx $ High Yield Corporate Bond ETF", desc: "US high-yield corporate credit", kind: "etf" },
  JNK: { name: "SPDR Bloomberg High Yield Bond ETF", desc: "US high-yield corporate credit", kind: "etf" },
  CWB: { name: "SPDR Bloomberg Convertible Securities ETF", desc: "US convertible bonds", kind: "etf" },
  PFF: { name: "iShares Preferred and Income Securities ETF", desc: "US preferred stock", kind: "etf" },
  MBB: { name: "iShares MBS ETF", desc: "US agency mortgage-backed securities", kind: "etf" },
  MUB: { name: "iShares National Muni Bond ETF", desc: "US investment-grade municipal bonds", kind: "etf" },
  EMB: { name: "iShares J.P. Morgan USD Emerging Markets Bond ETF", desc: "USD-denominated EM sovereign bonds", kind: "etf" },
  VNQ: { name: "Vanguard Real Estate ETF", desc: "US equity REITs", kind: "etf" },
  XHB: { name: "SPDR S&P Homebuilders ETF", desc: "US homebuilders & building products", kind: "etf" },
  XLU: { name: "Utilities Select Sector SPDR Fund", desc: "S&P 500 utilities sector", kind: "etf" },
  REM: { name: "iShares Mortgage Real Estate ETF", desc: "US mortgage REITs", kind: "etf" },
  KRE: { name: "SPDR S&P Regional Banking ETF", desc: "US regional banks", kind: "etf" },
  XLF: { name: "Financial Select Sector SPDR Fund", desc: "S&P 500 financials sector", kind: "etf" },
  SPY: { name: "SPDR S&P 500 ETF Trust", desc: "US large-cap equities", kind: "etf" },
  QQQ: { name: "Invesco QQQ Trust", desc: "Nasdaq-100 equities", kind: "etf" },
  IWM: { name: "iShares Russell 2000 ETF", desc: "US small-cap equities", kind: "etf" },
  EEM: { name: "iShares MSCI Emerging Markets ETF", desc: "Emerging-market equities", kind: "etf" },
  GLD: { name: "SPDR Gold Shares", desc: "Spot gold price", kind: "etf" },
  UUP: { name: "Invesco DB US Dollar Index Bullish Fund", desc: "US dollar index vs majors", kind: "etf" },
  "ES": { name: "E-mini S&P 500 futures", desc: "CME — US large-cap equity index", kind: "future" },
  "NQ": { name: "E-mini Nasdaq 100 futures", desc: "CME — tech-heavy equity index", kind: "future" },
  "YM": { name: "E-mini Dow futures", desc: "CBOT — blue-chip equity index", kind: "future" },
  "RTY": { name: "E-mini Russell 2000 futures", desc: "CME — US small-cap equity index", kind: "future" },
  "ZB": { name: "30-Year T-Bond futures", desc: "CBOT — long-end Treasury", kind: "future" },
  "ZN": { name: "10-Year T-Note futures", desc: "CBOT — intermediate Treasury", kind: "future" },
  "ZF": { name: "5-Year T-Note futures", desc: "CBOT — belly Treasury", kind: "future" },
  "ZT": { name: "2-Year T-Note futures", desc: "CBOT — front-end Treasury", kind: "future" },
  "CL": { name: "WTI Crude Oil futures", desc: "NYMEX — light sweet crude", kind: "future" },
  "GC": { name: "Gold futures", desc: "COMEX — gold", kind: "future" },
  "SI": { name: "Silver futures", desc: "COMEX — silver", kind: "future" },
  "HG": { name: "Copper futures", desc: "COMEX — copper", kind: "future" },
  "SOFR": { name: "3-Month SOFR futures", desc: "CME — overnight funding rate", kind: "future" },
  "VIX": { name: "VIX futures", desc: "Cboe — equity volatility index", kind: "future" },
  "DX": { name: "U.S. Dollar Index futures", desc: "ICE — dollar vs six majors", kind: "future" },
  "6B": { name: "British Pound futures", desc: "CME — GBP/USD FX", kind: "future" },
  "6E": { name: "Euro FX futures", desc: "CME — EUR/USD FX", kind: "future" },
  "6J": { name: "Japanese Yen futures", desc: "CME — JPY/USD FX", kind: "future" },
  NVDA: { name: "Nvidia", desc: "Technology", kind: "stock" },
  AAPL: { name: "Apple", desc: "Technology", kind: "stock" },
  MSFT: { name: "Microsoft", desc: "Technology", kind: "stock" },
  AMD: { name: "AMD", desc: "Technology", kind: "stock" },
  AVGO: { name: "Broadcom", desc: "Technology", kind: "stock" },
  INTC: { name: "Intel", desc: "Technology", kind: "stock" },
  QCOM: { name: "Qualcomm", desc: "Technology", kind: "stock" },
  TXN: { name: "Texas Instruments", desc: "Technology", kind: "stock" },
  AMAT: { name: "Applied Materials", desc: "Technology", kind: "stock" },
  LRCX: { name: "Lam Research", desc: "Technology", kind: "stock" },
  MU: { name: "Micron", desc: "Technology", kind: "stock" },
  KLAC: { name: "KLA", desc: "Technology", kind: "stock" },
  ADI: { name: "Analog Devices", desc: "Technology", kind: "stock" },
  MRVL: { name: "Marvell", desc: "Technology", kind: "stock" },
  ARM: { name: "Arm Holdings", desc: "Technology", kind: "stock" },
  SMCI: { name: "Super Micro", desc: "Technology", kind: "stock" },
  DELL: { name: "Dell", desc: "Technology", kind: "stock" },
  HPQ: { name: "HP", desc: "Technology", kind: "stock" },
  IBM: { name: "IBM", desc: "Technology", kind: "stock" },
  ORCL: { name: "Oracle", desc: "Technology", kind: "stock" },
  CRM: { name: "Salesforce", desc: "Technology", kind: "stock" },
  ADBE: { name: "Adobe", desc: "Technology", kind: "stock" },
  INTU: { name: "Intuit", desc: "Technology", kind: "stock" },
  NOW: { name: "ServiceNow", desc: "Technology", kind: "stock" },
  PANW: { name: "Palo Alto Networks", desc: "Technology", kind: "stock" },
  CRWD: { name: "CrowdStrike", desc: "Technology", kind: "stock" },
  FTNT: { name: "Fortinet", desc: "Technology", kind: "stock" },
  PLTR: { name: "Palantir", desc: "Technology", kind: "stock" },
  SNOW: { name: "Snowflake", desc: "Technology", kind: "stock" },
  DDOG: { name: "Datadog", desc: "Technology", kind: "stock" },
  NET: { name: "Cloudflare", desc: "Technology", kind: "stock" },
  MDB: { name: "MongoDB", desc: "Technology", kind: "stock" },
  SHOP: { name: "Shopify", desc: "Technology", kind: "stock" },
  XYZ: { name: "Block", desc: "Technology", kind: "stock" },
  PYPL: { name: "PayPal", desc: "Technology", kind: "stock" },
  COIN: { name: "Coinbase", desc: "Financials", kind: "stock" },
  MSTR: { name: "Strategy", desc: "Technology", kind: "stock" },
  TSLA: { name: "Tesla", desc: "Consumer Discretionary", kind: "stock" },
  AMZN: { name: "Amazon", desc: "Consumer Discretionary", kind: "stock" },
  HD: { name: "Home Depot", desc: "Consumer Discretionary", kind: "stock" },
  MCD: { name: "McDonald's", desc: "Consumer Discretionary", kind: "stock" },
  NKE: { name: "Nike", desc: "Consumer Discretionary", kind: "stock" },
  SBUX: { name: "Starbucks", desc: "Consumer Discretionary", kind: "stock" },
  BKNG: { name: "Booking", desc: "Consumer Discretionary", kind: "stock" },
  ABNB: { name: "Airbnb", desc: "Consumer Discretionary", kind: "stock" },
  RIVN: { name: "Rivian", desc: "Consumer Discretionary", kind: "stock" },
  LCID: { name: "Lucid", desc: "Consumer Discretionary", kind: "stock" },
  F: { name: "Ford", desc: "Consumer Discretionary", kind: "stock" },
  GM: { name: "General Motors", desc: "Consumer Discretionary", kind: "stock" },
  GME: { name: "GameStop", desc: "Consumer Discretionary", kind: "stock" },
  AMC: { name: "AMC Entertainment", desc: "Communication Services", kind: "stock" },
  GOOGL: { name: "Alphabet", desc: "Communication Services", kind: "stock" },
  GOOG: { name: "Alphabet", desc: "Communication Services", kind: "stock" },
  META: { name: "Meta", desc: "Communication Services", kind: "stock" },
  NFLX: { name: "Netflix", desc: "Communication Services", kind: "stock" },
  DIS: { name: "Disney", desc: "Communication Services", kind: "stock" },
  T: { name: "AT&T", desc: "Communication Services", kind: "stock" },
  VZ: { name: "Verizon", desc: "Communication Services", kind: "stock" },
  TMUS: { name: "T-Mobile", desc: "Communication Services", kind: "stock" },
  EA: { name: "Electronic Arts", desc: "Communication Services", kind: "stock" },
  TTWO: { name: "Take-Two", desc: "Communication Services", kind: "stock" },
  RBLX: { name: "Roblox", desc: "Communication Services", kind: "stock" },
  DJT: { name: "Trump Media", desc: "Communication Services", kind: "stock" },
  SNAP: { name: "Snap", desc: "Communication Services", kind: "stock" },
  PINS: { name: "Pinterest", desc: "Communication Services", kind: "stock" },
  JPM: { name: "JPMorgan", desc: "Financials", kind: "stock" },
  BAC: { name: "Bank of America", desc: "Financials", kind: "stock" },
  WFC: { name: "Wells Fargo", desc: "Financials", kind: "stock" },
  C: { name: "Citigroup", desc: "Financials", kind: "stock" },
  GS: { name: "Goldman Sachs", desc: "Financials", kind: "stock" },
  MS: { name: "Morgan Stanley", desc: "Financials", kind: "stock" },
  AXP: { name: "Amex", desc: "Financials", kind: "stock" },
  V: { name: "Visa", desc: "Financials", kind: "stock" },
  MA: { name: "Mastercard", desc: "Financials", kind: "stock" },
  COF: { name: "Capital One", desc: "Financials", kind: "stock" },
  SCHW: { name: "Charles Schwab", desc: "Financials", kind: "stock" },
  HOOD: { name: "Robinhood", desc: "Financials", kind: "stock" },
  SOFI: { name: "SoFi", desc: "Financials", kind: "stock" },
  BX: { name: "Blackstone", desc: "Financials", kind: "stock" },
  KKR: { name: "KKR", desc: "Financials", kind: "stock" },
  ARES: { name: "Ares", desc: "Financials", kind: "stock" },
  JNJ: { name: "Johnson & Johnson", desc: "Healthcare", kind: "stock" },
  UNH: { name: "UnitedHealth", desc: "Healthcare", kind: "stock" },
  LLY: { name: "Eli Lilly", desc: "Healthcare", kind: "stock" },
  PFE: { name: "Pfizer", desc: "Healthcare", kind: "stock" },
  MRK: { name: "Merck", desc: "Healthcare", kind: "stock" },
  ABBV: { name: "AbbVie", desc: "Healthcare", kind: "stock" },
  AMGN: { name: "Amgen", desc: "Healthcare", kind: "stock" },
  GILD: { name: "Gilead", desc: "Healthcare", kind: "stock" },
  BIIB: { name: "Biogen", desc: "Healthcare", kind: "stock" },
  REGN: { name: "Regeneron", desc: "Healthcare", kind: "stock" },
  VRTX: { name: "Vertex", desc: "Healthcare", kind: "stock" },
  ISRG: { name: "Intuitive Surgical", desc: "Healthcare", kind: "stock" },
  TMO: { name: "Thermo Fisher", desc: "Healthcare", kind: "stock" },
  DHR: { name: "Danaher", desc: "Healthcare", kind: "stock" },
  CVS: { name: "CVS Health", desc: "Healthcare", kind: "stock" },
  HCA: { name: "HCA", desc: "Healthcare", kind: "stock" },
  XOM: { name: "Exxon Mobil", desc: "Energy", kind: "stock" },
  CVX: { name: "Chevron", desc: "Energy", kind: "stock" },
  COP: { name: "ConocoPhillips", desc: "Energy", kind: "stock" },
  EOG: { name: "EOG Resources", desc: "Energy", kind: "stock" },
  SLB: { name: "SLB", desc: "Energy", kind: "stock" },
  OXY: { name: "Occidental", desc: "Energy", kind: "stock" },
  MPC: { name: "Marathon Petroleum", desc: "Energy", kind: "stock" },
  VLO: { name: "Valero", desc: "Energy", kind: "stock" },
  MARA: { name: "MARA Holdings", desc: "Energy", kind: "stock" },
  RIOT: { name: "Riot Platforms", desc: "Energy", kind: "stock" },
  BA: { name: "Boeing", desc: "Industrials", kind: "stock" },
  CAT: { name: "Caterpillar", desc: "Industrials", kind: "stock" },
  GE: { name: "GE Aerospace", desc: "Industrials", kind: "stock" },
  HON: { name: "Honeywell", desc: "Industrials", kind: "stock" },
  UPS: { name: "UPS", desc: "Industrials", kind: "stock" },
  FDX: { name: "FedEx", desc: "Industrials", kind: "stock" },
  LMT: { name: "Lockheed Martin", desc: "Industrials", kind: "stock" },
  RTX: { name: "RTX", desc: "Industrials", kind: "stock" },
  NOC: { name: "Northrop Grumman", desc: "Industrials", kind: "stock" },
  DAL: { name: "Delta", desc: "Industrials", kind: "stock" },
  UAL: { name: "United Airlines", desc: "Industrials", kind: "stock" },
  WMT: { name: "Walmart", desc: "Consumer Staples", kind: "stock" },
  COST: { name: "Costco", desc: "Consumer Staples", kind: "stock" },
  PG: { name: "Procter & Gamble", desc: "Consumer Staples", kind: "stock" },
  KO: { name: "Coca-Cola", desc: "Consumer Staples", kind: "stock" },
  PEP: { name: "PepsiCo", desc: "Consumer Staples", kind: "stock" },
  NEE: { name: "NextEra", desc: "Utilities", kind: "stock" },
  DUK: { name: "Duke Energy", desc: "Utilities", kind: "stock" },
  LIN: { name: "Linde", desc: "Materials", kind: "stock" },
  FCX: { name: "Freeport-McMoRan", desc: "Materials", kind: "stock" },
  NEM: { name: "Newmont", desc: "Materials", kind: "stock" },
  AMT: { name: "American Tower", desc: "Real Estate", kind: "stock" },
  PLD: { name: "Prologis", desc: "Real Estate", kind: "stock" },
  FNGR: { name: "FingerMotion", desc: "Technology", kind: "stock" },
  FLUX: { name: "Flux Power", desc: "Industrials", kind: "stock" },
  QTEX: { name: "QTREX Quantum", desc: "Technology", kind: "stock" },
  AMOD: { name: "Alpha Modus", desc: "Technology", kind: "stock" },
  SDEV: { name: "Stablecoin Development", desc: "Financials", kind: "stock" },
  NIVF: { name: "NewGenIvf Group", desc: "Healthcare", kind: "stock" },
  AAL: { name: "American Airlines", desc: "Industrials", kind: "stock" },
  SCKT: { name: "Socket Mobile", desc: "Technology", kind: "stock" },
  SPCX: { name: "Space Exploration Technologies", desc: "Industrials", kind: "stock" },
  NU: { name: "Nu Holdings", desc: "Financials", kind: "stock" },
  SCNX: { name: "Scienture Holdings", desc: "Healthcare", kind: "stock" },
  NVD: { name: "2x Short NVDA ETF", desc: "ETF", kind: "stock" },
  BITO: { name: "ProShares Bitcoin ETF", desc: "ETF", kind: "stock" },
  SOXS: { name: "Semiconductor Bear 3X", desc: "ETF", kind: "stock" },
  DDC: { name: "DDC Enterprise", desc: "Consumer Staples", kind: "stock" },
  MSTZ: { name: "2X Inverse MSTR ETF", desc: "ETF", kind: "stock" },
  RWM: { name: "Short Russell 2000", desc: "ETF", kind: "stock" },
  CYCU: { name: "Cycurion", desc: "Technology", kind: "stock" },
  ONDS: { name: "Ondas Holdings", desc: "Technology", kind: "stock" },
  PLUG: { name: "Plug Power", desc: "Industrials", kind: "stock" },
  CTVA: { name: "Corteva", desc: "Materials", kind: "stock" },
  // ---- Indices (EQTY table) ----
  SPX: { name: "S&P 500", desc: "US large-cap equity index", kind: "index" },
  NDX: { name: "Nasdaq-100", desc: "US large-cap tech equity index", kind: "index" },
  DJI: { name: "Dow Jones Industrial Average", desc: "US blue-chip equity index", kind: "index" },
  SX5E: { name: "Euro Stoxx 50", desc: "Eurozone blue-chip equity index", kind: "index" },
  DAX: { name: "DAX", desc: "German blue-chip equity index", kind: "index" },
  CAC: { name: "CAC 40", desc: "French blue-chip equity index", kind: "index" },
  UKX: { name: "FTSE 100", desc: "UK blue-chip equity index", kind: "index" },
  SMI: { name: "Swiss Market Index", desc: "Swiss blue-chip equity index", kind: "index" },
  NKX: { name: "Nikkei 225", desc: "Japanese equity index", kind: "index" },
  HSI: { name: "Hang Seng Index", desc: "Hong Kong equity index", kind: "index" },
  // ---- Single-stock movers universe ----
  A: { name: "Agilent Technologies", desc: "Healthcare", kind: "stock" },
  ADSK: { name: "Autodesk", desc: "Technology", kind: "stock" },
  ALNY: { name: "Alnylam Pharmaceuticals", desc: "Healthcare", kind: "stock" },
  APP: { name: "AppLovin", desc: "Technology", kind: "stock" },
  BKR: { name: "Baker Hughes", desc: "Energy", kind: "stock" },
  CDNS: { name: "Cadence Design Systems", desc: "Technology", kind: "stock" },
  CEG: { name: "Constellation Energy", desc: "Utilities", kind: "stock" },
  CHRW: { name: "C.H. Robinson", desc: "Industrials", kind: "stock" },
  CIEN: { name: "Ciena", desc: "Technology", kind: "stock" },
  CMCSA: { name: "Comcast", desc: "Communication Services", kind: "stock" },
  COO: { name: "Cooper Companies", desc: "Healthcare", kind: "stock" },
  CPRT: { name: "Copart", desc: "Industrials", kind: "stock" },
  CSCO: { name: "Cisco", desc: "Technology", kind: "stock" },
  DOC: { name: "Healthpeak Properties", desc: "Real Estate", kind: "stock" },
  DTE: { name: "DTE Energy", desc: "Utilities", kind: "stock" },
  DXCM: { name: "Dexcom", desc: "Healthcare", kind: "stock" },
  ECHO: { name: "EchoStar", desc: "Communication Services", kind: "stock" },
  FER: { name: "Ferrovial", desc: "Industrials", kind: "stock" },
  FFIV: { name: "F5", desc: "Technology", kind: "stock" },
  FRT: { name: "Federal Realty", desc: "Real Estate", kind: "stock" },
  GEN: { name: "Gen Digital", desc: "Technology", kind: "stock" },
  IDXX: { name: "IDEXX Laboratories", desc: "Healthcare", kind: "stock" },
  ILMN: { name: "Illumina", desc: "Healthcare", kind: "stock" },
  INCY: { name: "Incyte", desc: "Healthcare", kind: "stock" },
  KHC: { name: "Kraft Heinz", desc: "Consumer Staples", kind: "stock" },
  KMI: { name: "Kinder Morgan", desc: "Energy", kind: "stock" },
  LITE: { name: "Lumentum", desc: "Technology", kind: "stock" },
  LVS: { name: "Las Vegas Sands", desc: "Consumer Discretionary", kind: "stock" },
  MAR: { name: "Marriott", desc: "Consumer Discretionary", kind: "stock" },
  MELI: { name: "MercadoLibre", desc: "Consumer Discretionary", kind: "stock" },
  MGM: { name: "MGM Resorts", desc: "Consumer Discretionary", kind: "stock" },
  MKC: { name: "McCormick", desc: "Consumer Staples", kind: "stock" },
  MTD: { name: "Mettler Toledo", desc: "Healthcare", kind: "stock" },
  NTAP: { name: "NetApp", desc: "Technology", kind: "stock" },
  O: { name: "Realty Income", desc: "Real Estate", kind: "stock" },
  PAYX: { name: "Paychex", desc: "Industrials", kind: "stock" },
  PCAR: { name: "PACCAR", desc: "Industrials", kind: "stock" },
  PEG: { name: "Public Service Enterprise", desc: "Utilities", kind: "stock" },
  PNW: { name: "Pinnacle West", desc: "Utilities", kind: "stock" },
  PTC: { name: "PTC Inc", desc: "Technology", kind: "stock" },
  ROST: { name: "Ross Stores", desc: "Consumer Discretionary", kind: "stock" },
  RVTY: { name: "Revvity", desc: "Healthcare", kind: "stock" },
  SNPS: { name: "Synopsys", desc: "Technology", kind: "stock" },
  STX: { name: "Seagate", desc: "Technology", kind: "stock" },
  VST: { name: "Vistra", desc: "Utilities", kind: "stock" },
  VTR: { name: "Ventas", desc: "Real Estate", kind: "stock" },
  WBD: { name: "Warner Bros Discovery", desc: "Communication Services", kind: "stock" },
  WDC: { name: "Western Digital", desc: "Technology", kind: "stock" },
  WY: { name: "Weyerhaeuser", desc: "Real Estate", kind: "stock" },
  WYNN: { name: "Wynn Resorts", desc: "Consumer Discretionary", kind: "stock" },
  XEL: { name: "Xcel Energy", desc: "Utilities", kind: "stock" },
};

// Back-compat tuple map for equityhub's tickerMeta (name, sector).
export const STOCK_META = {};
for (const [k, v] of Object.entries(NAMES)) STOCK_META[k] = [v.name, v.kind === "stock" ? v.desc : v.kind.toUpperCase()];

export function symInfo(sym) {
  if (!sym) return null;
  return NAMES[String(sym).toUpperCase()] || null;
}

export function symName(sym) {
  const i = symInfo(sym);
  return i ? `${String(sym).toUpperCase()} — ${i.name}` : String(sym ?? "");
}

// Inline HTML for table cells: bold ticker + long name, truncated desc on wide screens.
export function symNameHtml(sym, maxDesc = 42) {
  const i = symInfo(sym);
  const s = String(sym ?? "").toUpperCase();
  if (!i) return `<b>${esc(s)}</b>`;
  const d = i.desc.length > maxDesc ? i.desc.slice(0, maxDesc - 1) + "…" : i.desc;
  return `<b>${esc(s)}</b> <span class="sym-name">${esc(i.name)}</span> ` +
    `<span class="sym-desc" title="${esc(i.desc)}">${esc(d)}</span>`;
}

