// names.js — central symbol dictionary: every ticker/ETF/future → long name + description.
// Harry (2026-10-06): 'so I know what I'm seeing.' Display inline, not just tooltip.
//
// Usage:
//   import { symInfo, symName, symNameHtml } from "../names.js";
//   symInfo("TLT") → { name, desc, kind }   (kind: stock|etf|future|other)
//   symName("TLT") → "TLT — iShares 20+ Year Treasury Bond ETF"
//   symNameHtml("TLT") → inline HTML with truncated desc for tight cells

const esc = (s) => String(s ?? "").replace(/[&<>"']/g, (c) =>
  ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));

export const NAMES = {
  TLT: { name: "iShares 20+ Year Treasury Bond ETF", desc: "Long-duration US Treasury bonds", kind: "etf" },
  IEF: { name: "iShares 7-10 Year Treasury Bond ETF", desc: "Intermediate-term US Treasury bonds", kind: "etf" },
  SHY: { name: "iShares 1-3 Year Treasury Bond ETF", desc: "Short-term US Treasury bonds", kind: "etf" },
  SHV: { name: "iShares Short Treasury Bond ETF", desc: "0-1 year US Treasury bills", kind: "etf" },
  BIL: { name: "SPDR Bloomberg 1-3 Month T-Bill ETF", desc: "Ultra-short Treasury bill cash proxy", kind: "etf" },
  TIP: { name: "iShares TIPS Bond ETF", desc: "Treasury inflation-protected securities", kind: "etf" },
  BKLN: { name: "Invesco Senior Loan ETF", desc: "Floating-rate leveraged loans", kind: "etf" },
  LQD: { name: "iShares iBoxx $ Investment Grade Corporate Bond ETF", desc: "US investment-grade corporate credit", kind: "etf" },
  ANGL: { name: "VanEck Fallen Angel High Yield Bond ETF", desc: "Downgraded-to-HY 'fallen angel' bonds", kind: "etf" },
  HYG: { name: "iShares iBoxx $ High Yield Corporate Bond ETF", desc: "US high-yield corporate credit", kind: "etf" },
  JNK: { name: "SPDR Bloomberg High Yield Bond ETF", desc: "US high-yield corporate credit", kind: "etf" },
  CWB: { name: "SPDR Bloomberg Convertible Securities ETF", desc: "US convertible bonds", kind: "etf" },
  PFF: { name: "iShares Preferred and Income Securities ETF", desc: "US preferred stock", kind: "etf" },
  MBB: { name: "iShares MBS ETF", desc: "US agency mortgage-backed securities", kind: "etf" },
  MUB: { name: "iShares National Muni Bond ETF", desc: "US investment-grade municipal bonds", kind: "etf" },
  EMB: { name: "iShares J.P. Morgan USD Emerging Markets Bond ETF", desc: "USD-denominated EM sovereign bonds", kind: "etf" },
  VNQ: { name: "Vanguard Real Estate ETF", desc: "US equity REITs", kind: "etf" },
  XHB: { name: "SPDR S&P Homebuilders ETF", desc: "US homebuilders & building products", kind: "etf" },
  XLU: { name: "Utilities Select Sector SPDR Fund", desc: "S&P 500 utilities sector", kind: "etf" },
  REM: { name: "iShares Mortgage Real Estate ETF", desc: "US mortgage REITs", kind: "etf" },
  KRE: { name: "SPDR S&P Regional Banking ETF", desc: "US regional banks", kind: "etf" },
  XLF: { name: "Financial Select Sector SPDR Fund", desc: "S&P 500 financials sector", kind: "etf" },
  SPY: { name: "SPDR S&P 500 ETF Trust", desc: "US large-cap equities", kind: "etf" },
  QQQ: { name: "Invesco QQQ Trust", desc: "Nasdaq-100 equities", kind: "etf" },
  IWM: { name: "iShares Russell 2000 ETF", desc: "US small-cap equities", kind: "etf" },
  EEM: { name: "iShares MSCI Emerging Markets ETF", desc: "Emerging-market equities", kind: "etf" },
  GLD: { name: "SPDR Gold Shares", desc: "Spot gold price", kind: "etf" },
  UUP: { name: "Invesco DB US Dollar Index Bullish Fund", desc: "US dollar index vs majors", kind: "etf" },
  "ES": { name: "E-mini S&P 500 futures", desc: "CME — US large-cap equity index", kind: "future" },
  "NQ": { name: "E-mini Nasdaq 100 futures", desc: "CME — tech-heavy equity index", kind: "future" },
  "YM": { name: "E-mini Dow futures", desc: "CBOT — blue-chip equity index", kind: "future" },
  "RTY": { name: "E-mini Russell 2000 futures", desc: "CME — US small-cap equity index", kind: "future" },
  "ZB": { name: "30-Year T-Bond futures", desc: "CBOT — long-end Treasury", kind: "future" },
  "ZN": { name: "10-Year T-Note futures", desc: "CBOT — intermediate Treasury", kind: "future" },
  "ZF": { name: "5-Year T-Note futures", desc: "CBOT — belly Treasury", kind: "future" },
  "ZT": { name: "2-Year T-Note futures", desc: "CBOT — front-end Treasury", kind: "future" },
  "CL": { name: "WTI Crude Oil futures", desc: "NYMEX — light sweet crude", kind: "future" },
  "GC": { name: "Gold futures", desc: "COMEX — gold", kind: "future" },
  "SI": { name: "Silver futures", desc: "COMEX — silver", kind: "future" },
  "HG": { name: "Copper futures", desc: "COMEX — copper", kind: "future" },
  "SOFR": { name: "3-Month SOFR futures", desc: "CME — overnight funding rate", kind: "future" },
  "VIX": { name: "VIX futures", desc: "Cboe — equity volatility index", kind: "future" },
  "DX": { name: "U.S. Dollar Index futures", desc: "ICE — dollar vs six majors", kind: "future" },
  "6B": { name: "British Pound futures", desc: "CME — GBP/USD FX", kind: "future" },
  "6E": { name: "Euro FX futures", desc: "CME — EUR/USD FX", kind: "future" },
  "6J": { name: "Japanese Yen futures", desc: "CME — JPY/USD FX", kind: "future" },
  NVDA: { name: "Nvidia", desc: "Technology", kind: "stock" },
  AAPL: { name: "Apple", desc: "Technology", kind: "stock" },
  MSFT: { name: "Microsoft", desc: "Technology", kind: "stock" },
  AMD: { name: "AMD", desc: "Technology", kind: "stock" },
  AVGO: { name: "Broadcom", desc: "Technology", kind: "stock" },
  INTC: { name: "Intel", desc: "Technology", kind: "stock" },
  QCOM: { name: "Qualcomm", desc: "Technology", kind: "stock" },
  TXN: { name: "Texas Instruments", desc: "Technology", kind: "stock" },
  AMAT: { name: "Applied Materials", desc: "Technology", kind: "stock" },
  LRCX: { name: "Lam Research", desc: "Technology", kind: "stock" },
  MU: { name: "Micron", desc: "Technology", kind: "stock" },
  KLAC: { name: "KLA", desc: "Technology", kind: "stock" },
  ADI: { name: "Analog Devices", desc: "Technology", kind: "stock" },
  MRVL: { name: "Marvell", desc: "Technology", kind: "stock" },
  ARM: { name: "Arm Holdings", desc: "Technology", kind: "stock" },
  SMCI: { name: "Super Micro", desc: "Technology", kind: "stock" },
  DELL: { name: "Dell", desc: "Technology", kind: "stock" },
  HPQ: { name: "HP", desc: "Technology", kind: "stock" },
  IBM: { name: "IBM", desc: "Technology", kind: "stock" },
  ORCL: { name: "Oracle", desc: "Technology", kind: "stock" },
  CRM: { name: "Salesforce", desc: "Technology", kind: "stock" },
  ADBE: { name: "Adobe", desc: "Technology", kind: "stock" },
  INTU: { name: "Intuit", desc: "Technology", kind: "stock" },
  NOW: { name: "ServiceNow", desc: "Technology", kind: "stock" },
  PANW: { name: "Palo Alto Networks", desc: "Technology", kind: "stock" },
  CRWD: { name: "CrowdStrike", desc: "Technology", kind: "stock" },
  FTNT: { name: "Fortinet", desc: "Technology", kind: "stock" },
  PLTR: { name: "Palantir", desc: "Technology", kind: "stock" },
  SNOW: { name: "Snowflake", desc: "Technology", kind: "stock" },
  DDOG: { name: "Datadog", desc: "Technology", kind: "stock" },
  NET: { name: "Cloudflare", desc: "Technology", kind: "stock" },
  MDB: { name: "MongoDB", desc: "Technology", kind: "stock" },
  SHOP: { name: "Shopify", desc: "Technology", kind: "stock" },
  XYZ: { name: "Block", desc: "Technology", kind: "stock" },
  PYPL: { name: "PayPal", desc: "Technology", kind: "stock" },
  COIN: { name: "Coinbase", desc: "Financials", kind: "stock" },
  MSTR: { name: "Strategy", desc: "Technology", kind: "stock" },
  TSLA: { name: "Tesla", desc: "Consumer Discretionary", kind: "stock" },
  AMZN: { name: "Amazon", desc: "Consumer Discretionary", kind: "stock" },
  HD: { name: "Home Depot", desc: "Consumer Discretionary", kind: "stock" },
  MCD: { name: "McDonald's", desc: "Consumer Discretionary", kind: "stock" },
  NKE: { name: "Nike", desc: "Consumer Discretionary", kind: "stock" },
  SBUX: { name: "Starbucks", desc: "Consumer Discretionary", kind: "stock" },
  BKNG: { name: "Booking", desc: "Consumer Discretionary", kind: "stock" },
  ABNB: { name: "Airbnb", desc: "Consumer Discretionary", kind: "stock" },
  RIVN: { name: "Rivian", desc: "Consumer Discretionary", kind: "stock" },
  LCID: { name: "Lucid", desc: "Consumer Discretionary", kind: "stock" },
  F: { name: "Ford", desc: "Consumer Discretionary", kind: "stock" },
  GM: { name: "General Motors", desc: "Consumer Discretionary", kind: "stock" },
  GME: { name: "GameStop", desc: "Consumer Discretionary", kind: "stock" },
  AMC: { name: "AMC Entertainment", desc: "Communication Services", kind: "stock" },
  GOOGL: { name: "Alphabet", desc: "Communication Services", kind: "stock" },
  GOOG: { name: "Alphabet", desc: "Communication Services", kind: "stock" },
  META: { name: "Meta", desc: "Communication Services", kind: "stock" },
  NFLX: { name: "Netflix", desc: "Communication Services", kind: "stock" },
  DIS: { name: "Disney", desc: "Communication Services", kind: "stock" },
  T: { name: "AT&T", desc: "Communication Services", kind: "stock" },
  VZ: { name: "Verizon", desc: "Communication Services", kind: "stock" },
  TMUS: { name: "T-Mobile", desc: "Communication Services", kind: "stock" },
  EA: { name: "Electronic Arts", desc: "Communication Services", kind: "stock" },
  TTWO: { name: "Take-Two", desc: "Communication Services", kind: "stock" },
  RBLX: { name: "Roblox", desc: "Communication Services", kind: "stock" },
  DJT: { name: "Trump Media", desc: "Communication Services", kind: "stock" },
  SNAP: { name: "Snap", desc: "Communication Services", kind: "stock" },
  PINS: { name: "Pinterest", desc: "Communication Services", kind: "stock" },
  JPM: { name: "JPMorgan", desc: "Financials", kind: "stock" },
  BAC: { name: "Bank of America", desc: "Financials", kind: "stock" },
  WFC: { name: "Wells Fargo", desc: "Financials", kind: "stock" },
  C: { name: "Citigroup", desc: "Financials", kind: "stock" },
  GS: { name: "Goldman Sachs", desc: "Financials", kind: "stock" },
  MS: { name: "Morgan Stanley", desc: "Financials", kind: "stock" },
  AXP: { name: "Amex", desc: "Financials", kind: "stock" },
  V: { name: "Visa", desc: "Financials", kind: "stock" },
  MA: { name: "Mastercard", desc: "Financials", kind: "stock" },
  COF: { name: "Capital One", desc: "Financials", kind: "stock" },
  SCHW: { name: "Charles Schwab", desc: "Financials", kind: "stock" },
  HOOD: { name: "Robinhood", desc: "Financials", kind: "stock" },
  SOFI: { name: "SoFi", desc: "Financials", kind: "stock" },
  BX: { name: "Blackstone", desc: "Financials", kind: "stock" },
  KKR: { name: "KKR", desc: "Financials", kind: "stock" },
  ARES: { name: "Ares", desc: "Financials", kind: "stock" },
  JNJ: { name: "Johnson & Johnson", desc: "Healthcare", kind: "stock" },
  UNH: { name: "UnitedHealth", desc: "Healthcare", kind: "stock" },
  LLY: { name: "Eli Lilly", desc: "Healthcare", kind: "stock" },
  PFE: { name: "Pfizer", desc: "Healthcare", kind: "stock" },
  MRK: { name: "Merck", desc: "Healthcare", kind: "stock" },
  ABBV: { name: "AbbVie", desc: "Healthcare", kind: "stock" },
  AMGN: { name: "Amgen", desc: "Healthcare", kind: "stock" },
  GILD: { name: "Gilead", desc: "Healthcare", kind: "stock" },
  BIIB: { name: "Biogen", desc: "Healthcare", kind: "stock" },
  REGN: { name: "Regeneron", desc: "Healthcare", kind: "stock" },
  VRTX: { name: "Vertex", desc: "Healthcare", kind: "stock" },
  ISRG: { name: "Intuitive Surgical", desc: "Healthcare", kind: "stock" },
  TMO: { name: "Thermo Fisher", desc: "Healthcare", kind: "stock" },
  DHR: { name: "Danaher", desc: "Healthcare", kind: "stock" },
  CVS: { name: "CVS Health", desc: "Healthcare", kind: "stock" },
  HCA: { name: "HCA", desc: "Healthcare", kind: "stock" },
  XOM: { name: "Exxon Mobil", desc: "Energy", kind: "stock" },
  CVX: { name: "Chevron", desc: "Energy", kind: "stock" },
  COP: { name: "ConocoPhillips", desc: "Energy", kind: "stock" },
  EOG: { name: "EOG Resources", desc: "Energy", kind: "stock" },
  SLB: { name: "SLB", desc: "Energy", kind: "stock" },
  OXY: { name: "Occidental", desc: "Energy", kind: "stock" },
  MPC: { name: "Marathon Petroleum", desc: "Energy", kind: "stock" },
  VLO: { name: "Valero", desc: "Energy", kind: "stock" },
  MARA: { name: "MARA Holdings", desc: "Energy", kind: "stock" },
  RIOT: { name: "Riot Platforms", desc: "Energy", kind: "stock" },
  BA: { name: "Boeing", desc: "Industrials", kind: "stock" },
  CAT: { name: "Caterpillar", desc: "Industrials", kind: "stock" },
  GE: { name: "GE Aerospace", desc: "Industrials", kind: "stock" },
  HON: { name: "Honeywell", desc: "Industrials", kind: "stock" },
  UPS: { name: "UPS", desc: "Industrials", kind: "stock" },
  FDX: { name: "FedEx", desc: "Industrials", kind: "stock" },
  LMT: { name: "Lockheed Martin", desc: "Industrials", kind: "stock" },
  RTX: { name: "RTX", desc: "Industrials", kind: "stock" },
  NOC: { name: "Northrop Grumman", desc: "Industrials", kind: "stock" },
  DAL: { name: "Delta", desc: "Industrials", kind: "stock" },
  UAL: { name: "United Airlines", desc: "Industrials", kind: "stock" },
  WMT: { name: "Walmart", desc: "Consumer Staples", kind: "stock" },
  COST: { name: "Costco", desc: "Consumer Staples", kind: "stock" },
  PG: { name: "Procter & Gamble", desc: "Consumer Staples", kind: "stock" },
  KO: { name: "Coca-Cola", desc: "Consumer Staples", kind: "stock" },
  PEP: { name: "PepsiCo", desc: "Consumer Staples", kind: "stock" },
  NEE: { name: "NextEra", desc: "Utilities", kind: "stock" },
  DUK: { name: "Duke Energy", desc: "Utilities", kind: "stock" },
  LIN: { name: "Linde", desc: "Materials", kind: "stock" },
  FCX: { name: "Freeport-McMoRan", desc: "Materials", kind: "stock" },
  NEM: { name: "Newmont", desc: "Materials", kind: "stock" },
  AMT: { name: "American Tower", desc: "Real Estate", kind: "stock" },
  PLD: { name: "Prologis", desc: "Real Estate", kind: "stock" },
  FNGR: { name: "FingerMotion", desc: "Technology", kind: "stock" },
  FLUX: { name: "Flux Power", desc: "Industrials", kind: "stock" },
  QTEX: { name: "QTREX Quantum", desc: "Technology", kind: "stock" },
  AMOD: { name: "Alpha Modus", desc: "Technology", kind: "stock" },
  SDEV: { name: "Stablecoin Development", desc: "Financials", kind: "stock" },
  NIVF: { name: "NewGenIvf Group", desc: "Healthcare", kind: "stock" },
  AAL: { name: "American Airlines", desc: "Industrials", kind: "stock" },
  SCKT: { name: "Socket Mobile", desc: "Technology", kind: "stock" },
  SPCX: { name: "Space Exploration Technologies", desc: "Industrials", kind: "stock" },
  NU: { name: "Nu Holdings", desc: "Financials", kind: "stock" },
  SCNX: { name: "Scienture Holdings", desc: "Healthcare", kind: "stock" },
  NVD: { name: "2x Short NVDA ETF", desc: "ETF", kind: "stock" },
  BITO: { name: "ProShares Bitcoin ETF", desc: "ETF", kind: "stock" },
  SOXS: { name: "Semiconductor Bear 3X", desc: "ETF", kind: "stock" },
  DDC: { name: "DDC Enterprise", desc: "Consumer Staples", kind: "stock" },
  MSTZ: { name: "2X Inverse MSTR ETF", desc: "ETF", kind: "stock" },
  RWM: { name: "Short Russell 2000", desc: "ETF", kind: "stock" },
  CYCU: { name: "Cycurion", desc: "Technology", kind: "stock" },
  ONDS: { name: "Ondas Holdings", desc: "Technology", kind: "stock" },
  PLUG: { name: "Plug Power", desc: "Industrials", kind: "stock" },
  CTVA: { name: "Corteva", desc: "Materials", kind: "stock" },
  // ---- Indices (EQTY table) ----
  SPX: { name: "S&P 500", desc: "US large-cap equity index", kind: "index" },
  NDX: { name: "Nasdaq-100", desc: "US large-cap tech equity index", kind: "index" },
  DJI: { name: "Dow Jones Industrial Average", desc: "US blue-chip equity index", kind: "index" },
  SX5E: { name: "Euro Stoxx 50", desc: "Eurozone blue-chip equity index", kind: "index" },
  DAX: { name: "DAX", desc: "German blue-chip equity index", kind: "index" },
  CAC: { name: "CAC 40", desc: "French blue-chip equity index", kind: "index" },
  UKX: { name: "FTSE 100", desc: "UK blue-chip equity index", kind: "index" },
  SMI: { name: "Swiss Market Index", desc: "Swiss blue-chip equity index", kind: "index" },
  NKX: { name: "Nikkei 225", desc: "Japanese equity index", kind: "index" },
  HSI: { name: "Hang Seng Index", desc: "Hong Kong equity index", kind: "index" },
  // ---- Single-stock movers universe ----
  A: { name: "Agilent Technologies", desc: "Healthcare", kind: "stock" },
  ADSK: { name: "Autodesk", desc: "Technology", kind: "stock" },
  ALNY: { name: "Alnylam Pharmaceuticals", desc: "Healthcare", kind: "stock" },
  APP: { name: "AppLovin", desc: "Technology", kind: "stock" },
  BKR: { name: "Baker Hughes", desc: "Energy", kind: "stock" },
  CDNS: { name: "Cadence Design Systems", desc: "Technology", kind: "stock" },
  CEG: { name: "Constellation Energy", desc: "Utilities", kind: "stock" },
  CHRW: { name: "C.H. Robinson", desc: "Industrials", kind: "stock" },
  CIEN: { name: "Ciena", desc: "Technology", kind: "stock" },
  CMCSA: { name: "Comcast", desc: "Communication Services", kind: "stock" },
  COO: { name: "Cooper Companies", desc: "Healthcare", kind: "stock" },
  CPRT: { name: "Copart", desc: "Industrials", kind: "stock" },
  CSCO: { name: "Cisco", desc: "Technology", kind: "stock" },
  DOC: { name: "Healthpeak Properties", desc: "Real Estate", kind: "stock" },
  DTE: { name: "DTE Energy", desc: "Utilities", kind: "stock" },
  DXCM: { name: "Dexcom", desc: "Healthcare", kind: "stock" },
  ECHO: { name: "EchoStar", desc: "Communication Services", kind: "stock" },
  FER: { name: "Ferrovial", desc: "Industrials", kind: "stock" },
  FFIV: { name: "F5", desc: "Technology", kind: "stock" },
  FRT: { name: "Federal Realty", desc: "Real Estate", kind: "stock" },
  GEN: { name: "Gen Digital", desc: "Technology", kind: "stock" },
  IDXX: { name: "IDEXX Laboratories", desc: "Healthcare", kind: "stock" },
  ILMN: { name: "Illumina", desc: "Healthcare", kind: "stock" },
  INCY: { name: "Incyte", desc: "Healthcare", kind: "stock" },
  KHC: { name: "Kraft Heinz", desc: "Consumer Staples", kind: "stock" },
  KMI: { name: "Kinder Morgan", desc: "Energy", kind: "stock" },
  LITE: { name: "Lumentum", desc: "Technology", kind: "stock" },
  LVS: { name: "Las Vegas Sands", desc: "Consumer Discretionary", kind: "stock" },
  MAR: { name: "Marriott", desc: "Consumer Discretionary", kind: "stock" },
  MELI: { name: "MercadoLibre", desc: "Consumer Discretionary", kind: "stock" },
  MGM: { name: "MGM Resorts", desc: "Consumer Discretionary", kind: "stock" },
  MKC: { name: "McCormick", desc: "Consumer Staples", kind: "stock" },
  MTD: { name: "Mettler Toledo", desc: "Healthcare", kind: "stock" },
  NTAP: { name: "NetApp", desc: "Technology", kind: "stock" },
  O: { name: "Realty Income", desc: "Real Estate", kind: "stock" },
  PAYX: { name: "Paychex", desc: "Industrials", kind: "stock" },
  PCAR: { name: "PACCAR", desc: "Industrials", kind: "stock" },
  PEG: { name: "Public Service Enterprise", desc: "Utilities", kind: "stock" },
  PNW: { name: "Pinnacle West", desc: "Utilities", kind: "stock" },
  PTC: { name: "PTC Inc", desc: "Technology", kind: "stock" },
  ROST: { name: "Ross Stores", desc: "Consumer Discretionary", kind: "stock" },
  RVTY: { name: "Revvity", desc: "Healthcare", kind: "stock" },
  SNPS: { name: "Synopsys", desc: "Technology", kind: "stock" },
  STX: { name: "Seagate", desc: "Technology", kind: "stock" },
  VST: { name: "Vistra", desc: "Utilities", kind: "stock" },
  VTR: { name: "Ventas", desc: "Real Estate", kind: "stock" },
  WBD: { name: "Warner Bros Discovery", desc: "Communication Services", kind: "stock" },
  WDC: { name: "Western Digital", desc: "Technology", kind: "stock" },
  WY: { name: "Weyerhaeuser", desc: "Real Estate", kind: "stock" },
  WYNN: { name: "Wynn Resorts", desc: "Consumer Discretionary", kind: "stock" },
  XEL: { name: "Xcel Energy", desc: "Utilities", kind: "stock" },
  // Fixed income expansion (Harry 2026-10-06)
  GOVT: { name: "iShares US Treasury Bond ETF", desc: "Broad US Treasury bonds", kind: "etf" },
  VGIT: { name: "Vanguard Intermediate-Term Treasury ETF", desc: "3-10 year US Treasuries", kind: "etf" },
  VGLT: { name: "Vanguard Long-Term Treasury ETF", desc: "10+ year US Treasuries", kind: "etf" },
  SCHR: { name: "Schwab Intermediate-Term US Treasury ETF", desc: "3-10 year US Treasuries", kind: "etf" },
  SCHQ: { name: "Schwab Long-Term US Treasury ETF", desc: "10+ year US Treasuries", kind: "etf" },
  SPTL: { name: "SPDR Portfolio Long Term Treasury ETF", desc: "10+ year US Treasuries", kind: "etf" },
  EDV: { name: "Vanguard Extended Duration Treasury ETF", desc: "20-30 year STRIPS, max duration", kind: "etf" },
  ZROZ: { name: "PIMCO 25+ Year Zero Coupon US Treasury ETF", desc: "Long zero-coupon Treasuries", kind: "etf" },
  TYD: { name: "Direxion Daily 7-10 Year Treasury Bull 3X", desc: "3x daily 7-10Y Treasury", kind: "etf" },
  UST: { name: "ProShares Ultra 7-10 Year Treasury", desc: "2x daily 7-10Y Treasury", kind: "etf" },
  TBIL: { name: "USCF Treasury Bill ETF", desc: "Short-term T-bills", kind: "etf" },
  TFLO: { name: "iShares Treasury Floating Rate Bond ETF", desc: "Floating-rate Treasury notes", kind: "etf" },
  VGSH: { name: "Vanguard Short-Term Treasury ETF", desc: "1-3 year US Treasuries", kind: "etf" },
  USFR: { name: "WisdomTree Floating Rate Treasury Fund", desc: "Floating-rate Treasury notes", kind: "etf" },
  VCIT: { name: "Vanguard Intermediate-Term Corporate Bond ETF", desc: "5-10 year IG corporates", kind: "etf" },
  VCSH: { name: "Vanguard Short-Term Corporate Bond ETF", desc: "1-5 year IG corporates", kind: "etf" },
  SPIB: { name: "SPDR Portfolio Intermediate Term Corporate Bond ETF", desc: "1-10 year IG corporates", kind: "etf" },
  SPSB: { name: "SPDR Portfolio Short Term Corporate Bond ETF", desc: "1-3 year IG corporates", kind: "etf" },
  IGSB: { name: "iShares 1-5 Year Investment Grade Corporate Bond ETF", desc: "Short-term IG corporates", kind: "etf" },
  IGIB: { name: "iShares 5-10 Year Investment Grade Corporate Bond ETF", desc: "Intermediate IG corporates", kind: "etf" },
  USIG: { name: "iShares Broad USD Investment Grade Corporate Bond ETF", desc: "Broad IG corporates", kind: "etf" },
  LQDH: { name: "iShares Interest Rate Hedged Corporate Bond ETF", desc: "IG corporates, rate-hedged", kind: "etf" },
  SJNK: { name: "SPDR Bloomberg Short Term High Yield Bond ETF", desc: "Short-term high yield", kind: "etf" },
  HYLB: { name: "Xtrackers USD High Yield Corporate Bond ETF", desc: "US high yield, low fee", kind: "etf" },
  USHY: { name: "iShares Broad USD High Yield Corporate Bond ETF", desc: "Broad US high yield", kind: "etf" },
  SHYG: { name: "iShares 0-5 Year High Yield Corporate Bond ETF", desc: "Short-term high yield", kind: "etf" },
  VMBS: { name: "Vanguard Mortgage-Backed Securities ETF", desc: "US agency MBS", kind: "etf" },
  SPMB: { name: "SPDR Portfolio Mortgage Backed Bond ETF", desc: "US agency MBS", kind: "etf" },
  VTEB: { name: "Vanguard Tax-Exempt Bond ETF", desc: "National municipal bonds", kind: "etf" },
  SUB: { name: "iShares Short-Term National Muni Bond ETF", desc: "Short-term munis", kind: "etf" },
  SHM: { name: "SPDR Nuveen Bloomberg Short Term Municipal Bond ETF", desc: "Short-term munis", kind: "etf" },
  TFI: { name: "SPDR Nuveen Bloomberg Municipal Bond ETF", desc: "Investment-grade munis", kind: "etf" },
  HYD: { name: "VanEck High Yield Muni ETF", desc: "High-yield municipal bonds", kind: "etf" },
  SCHP: { name: "Schwab US TIPS ETF", desc: "Treasury inflation-protected securities", kind: "etf" },
  VTIP: { name: "Vanguard Short-Term Inflation-Protected Securities ETF", desc: "Short-term TIPS", kind: "etf" },
  STIP: { name: "iShares 0-5 Year TIPS Bond ETF", desc: "Short-term TIPS", kind: "etf" },
  SRLN: { name: "SPDR Blackstone Senior Loan ETF", desc: "Floating-rate senior loans", kind: "etf" },
  AAA: { name: "BondBloxx AAA Rated CLO ETF", desc: "AAA-rated CLO tranches", kind: "etf" },
  PGX: { name: "Invesco Preferred ETF", desc: "US preferred stock", kind: "etf" },
  PFXF: { name: "VanEck Preferred Securities ex Financials ETF", desc: "Preferreds ex-financials", kind: "etf" },
  SCHZ: { name: "Schwab US Aggregate Bond ETF", desc: "Total US bond market", kind: "etf" },
  SPAB: { name: "SPDR Portfolio Aggregate Bond ETF", desc: "Total US bond market", kind: "etf" },
  IUSB: { name: "iShares Core Total USD Bond Market ETF", desc: "Total US bond market", kind: "etf" },
  BNDX: { name: "Vanguard Total International Bond ETF", desc: "Hedged international bonds", kind: "etf" },
  IAGG: { name: "iShares Core International Aggregate Bond ETF", desc: "Hedged international bonds", kind: "etf" },
  VWOB: { name: "Vanguard Emerging Markets Government Bond ETF", desc: "EM government bonds", kind: "etf" },
  PCY: { name: "Invesco Emerging Markets Sovereign Debt ETF", desc: "EM sovereign debt", kind: "etf" },
  // Leveraged / inverse (Harry 2026-10-06)
  TQQQ: { name: "ProShares UltraPro QQQ", desc: "3x daily Nasdaq-100", kind: "etf" },
  SQQQ: { name: "ProShares UltraPro Short QQQ", desc: "-3x daily Nasdaq-100", kind: "etf" },
  TNA: { name: "Direxion Daily Small Cap Bull 3X", desc: "3x daily Russell 2000", kind: "etf" },
  TZA: { name: "Direxion Daily Small Cap Bear 3X", desc: "-3x daily Russell 2000", kind: "etf" },
  SPXL: { name: "Direxion Daily S&P 500 Bull 3X", desc: "3x daily S&P 500", kind: "etf" },
  SPXS: { name: "Direxion Daily S&P 500 Bear 3X", desc: "-3x daily S&P 500", kind: "etf" },
  UPRO: { name: "ProShares UltraPro S&P 500", desc: "3x daily S&P 500", kind: "etf" },
  SDS: { name: "ProShares UltraShort S&P 500", desc: "-2x daily S&P 500", kind: "etf" },
  QLD: { name: "ProShares Ultra QQQ", desc: "2x daily Nasdaq-100", kind: "etf" },
  QID: { name: "ProShares UltraShort QQQ", desc: "-2x daily Nasdaq-100", kind: "etf" },
  UVXY: { name: "ProShares Ultra VIX Short-Term Futures ETF", desc: "1.5x daily short-term VIX futures", kind: "etf" },
  SVXY: { name: "ProShares Short VIX Short-Term Futures ETF", desc: "-0.5x daily short-term VIX futures", kind: "etf" },
  TMF: { name: "Direxion Daily 20+ Year Treasury Bull 3X", desc: "3x daily long Treasuries", kind: "etf" },
  TMV: { name: "Direxion Daily 20+ Year Treasury Bear 3X", desc: "-3x daily long Treasuries", kind: "etf" },
  TBT: { name: "ProShares UltraShort 20+ Year Treasury", desc: "-2x daily long Treasuries", kind: "etf" },
  SOXL: { name: "Direxion Daily Semiconductor Bull 3X", desc: "3x daily semiconductors", kind: "etf" },
  SOXS: { name: "Direxion Daily Semiconductor Bear 3X", desc: "-3x daily semiconductors", kind: "etf" },
  LABU: { name: "Direxion Daily S&P Biotech Bull 3X", desc: "3x daily biotech", kind: "etf" },
  LABD: { name: "Direxion Daily S&P Biotech Bear 3X", desc: "-3x daily biotech", kind: "etf" },
  NUGT: { name: "Direxion Daily Gold Miners Bull 2X", desc: "2x daily gold miners", kind: "etf" },
  DUST: { name: "Direxion Daily Gold Miners Bear 2X", desc: "-2x daily gold miners", kind: "etf" },
  JNUG: { name: "Direxion Daily Junior Gold Miners Bull 2X", desc: "2x daily junior gold miners", kind: "etf" },
  JDST: { name: "Direxion Daily Junior Gold Miners Bear 2X", desc: "-2x daily junior gold miners", kind: "etf" },
  FAS: { name: "Direxion Daily Financial Bull 3X", desc: "3x daily financials", kind: "etf" },
  FAZ: { name: "Direxion Daily Financial Bear 3X", desc: "-3x daily financials", kind: "etf" },
  EDC: { name: "Direxion Daily MSCI Emerging Markets Bull 3X", desc: "3x daily emerging markets", kind: "etf" },
  EDZ: { name: "Direxion Daily MSCI Emerging Markets Bear 3X", desc: "-3x daily emerging markets", kind: "etf" },
  YINN: { name: "Direxion Daily FTSE China Bull 3X", desc: "3x daily China", kind: "etf" },
  YANG: { name: "Direxion Daily FTSE China Bear 3X", desc: "-3x daily China", kind: "etf" },
  TECL: { name: "Direxion Daily Technology Bull 3X", desc: "3x daily technology", kind: "etf" },
  TECS: { name: "Direxion Daily Technology Bear 3X", desc: "-3x daily technology", kind: "etf" },
  FNGU: { name: "MicroSectors FANG+ 3X Leveraged ETN", desc: "3x daily FANG+ stocks", kind: "etf" },
  FNGD: { name: "MicroSectors FANG+ -3X Inverse Leveraged ETN", desc: "-3x daily FANG+ stocks", kind: "etf" },
  BULZ: { name: "MicroSectors Solactive FANG Innovation 3X", desc: "3x daily FANG innovation", kind: "etf" },
  BERZ: { name: "MicroSectors Solactive FANG Innovation -3X", desc: "-3x daily FANG innovation", kind: "etf" },
  TSLL: { name: "Direxion Daily TSLA Bull 2X", desc: "2x daily Tesla (single-stock)", kind: "etf" },
  NVDL: { name: "GraniteShares 2x Long NVDA Daily ETF", desc: "2x daily Nvidia (single-stock)", kind: "etf" },
  // AI-themed (Harry 2026-10-06)
  BOTZ: { name: "Global X Robotics & Artificial Intelligence ETF", desc: "Robotics and AI companies", kind: "etf" },
  AIQ: { name: "Global X Artificial Intelligence & Technology ETF", desc: "AI and technology companies", kind: "etf" },
  WTAI: { name: "WisdomTree Artificial Intelligence & Innovation Fund", desc: "AI innovation companies", kind: "etf" },
  THNQ: { name: "Robo Global Artificial Intelligence ETF", desc: "AI ecosystem companies", kind: "etf" },
  ROBT: { name: "First Trust Nasdaq Artificial Intelligence & Robotics ETF", desc: "AI and robotics", kind: "etf" },
  ROBO: { name: "Robo Global Robotics & Automation ETF", desc: "Robotics and automation", kind: "etf" },
  XAIX: { name: "Xtrackers Artificial Intelligence & Big Data ETF", desc: "AI and big data companies", kind: "etf" },
  // Floaters / ABS / CMBS (Harry 2026-10-06)
  FLOT: { name: "iShares Floating Rate Bond ETF", desc: "Floating-rate investment-grade notes", kind: "etf" },
  FLRN: { name: "SPDR Bloomberg Investment Grade Floating Rate ETF", desc: "Floating-rate IG corporate notes", kind: "etf" },
  JABS: { name: "Janus Henderson ABS ETF", desc: "Asset-backed securities", kind: "etf" },
  CMBS: { name: "iShares CMBS ETF", desc: "Commercial mortgage-backed securities", kind: "etf" },
  // Crypto-equity ETFs (Harry 2026-10-06): miners, exchanges, futures
  BKCH: { name: "Global X Blockchain ETF", desc: "Blockchain technology companies", kind: "etf" },
  WGMI: { name: "Valkyrie Bitcoin Miners ETF", desc: "Bitcoin mining companies", kind: "etf" },
  BITQ: { name: "Bitwise Crypto Industry Innovators ETF", desc: "Crypto industry companies", kind: "etf" },
  DAPP: { name: "VanEck Digital Transformation ETF", desc: "Digital asset ecosystem companies", kind: "etf" },
  BLOK: { name: "Amplify Transformational Data Sharing ETF", desc: "Blockchain technology companies", kind: "etf" },
  BITO: { name: "ProShares Bitcoin Strategy ETF", desc: "Bitcoin futures (not spot)", kind: "etf" },
  // BDCs (Harry 2026-10-06): publicly traded business development companies
  ARCC: { name: "Ares Capital Corporation", desc: "BDC — middle-market lending", kind: "stock" },
  MAIN: { name: "Main Street Capital Corporation", desc: "BDC — lower middle-market lending", kind: "stock" },
  HTGC: { name: "Hercules Capital", desc: "BDC — venture/tech lending", kind: "stock" },
  GBDC: { name: "Golub Capital BDC", desc: "BDC — middle-market lending", kind: "stock" },
  BXSL: { name: "Blackstone Secured Lending Fund", desc: "BDC — senior secured loans", kind: "stock" },
  OCSL: { name: "Oaktree Specialty Lending Corp", desc: "BDC — middle-market lending", kind: "stock" },
  PSEC: { name: "Prospect Capital Corporation", desc: "BDC — middle-market lending", kind: "stock" },
  NMFC: { name: "New Mountain Finance Corp", desc: "BDC — defensive growth lending", kind: "stock" },
  TCPC: { name: "BlackRock TCP Capital Corp", desc: "BDC — middle-market lending", kind: "stock" },
};

// Back-compat tuple map for equityhub's tickerMeta (name, sector).
export const STOCK_META = {};
for (const [k, v] of Object.entries(NAMES)) STOCK_META[k] = [v.name, v.kind === "stock" ? v.desc : v.kind.toUpperCase()];

export function symInfo(sym) {
  if (!sym) return null;
  return NAMES[String(sym).toUpperCase()] || null;
}

export function symName(sym) {
  const i = symInfo(sym);
  return i ? `${String(sym).toUpperCase()} — ${i.name}` : String(sym ?? "");
}

// Inline HTML for table cells: bold ticker + long name, truncated desc on wide screens.
export function symNameHtml(sym, maxDesc = 42) {
  const i = symInfo(sym);
  const s = String(sym ?? "").toUpperCase();
  if (!i) return `<b>${esc(s)}</b>`;
  const d = i.desc.length > maxDesc ? i.desc.slice(0, maxDesc - 1) + "…" : i.desc;
  return `<b>${esc(s)}</b> <span class="sym-name">${esc(i.name)}</span> ` +
    `<span class="sym-desc" title="${esc(i.desc)}">${esc(d)}</span>`;
}

